config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'habits#index'
  get 'welcome/home'
  resources :habits do
    member do
      post :plus
      post :minus
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  # TODO: Fix flash notification timeOut for turbo stream
  # TODO: Implement awards for habits
  # TODO: Implement user cannot plus more than date last count and current date
  # TODO: Add no habits banner if no habits presents
  # TODO: Style session pages
  # TODO: show habits count
end

app/models/habit.rb
class Habit < ApplicationRecord
    belongs_to :user, counter_cache: :habits_count, touch: true

    
    validates :name, presence: true
    validates :count, presence: true

    scope :ordered, -> { order(updated_at: :desc) }

     before_update :check_count

    def check_count
        self.count = 0 if count < 0
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :habits, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    end
  

end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_habit, only: %i[ show edit update destroy plus minus ]


  def index
    @habits = current_user.habits.ordered
    @habit = current_user.habits.build
  end

  def show
  end

  def new
    @habit = current_user.habits.build
  end

  def create
    @habit = current_user.habits.build(habit_params)

    respond_to do |format|
      if @habit.save
        format.html { redirect_to habits_path, notice: "Habit was successfully create!." }
        format.turbo_stream { flash.now[:notice] = "Habit was successfully create!," }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @habit.update(habit_params)

      respond_to do |format|
        format.html { redirect_to habits_path, notice: "Habit was successfully updated!." }
        format.turbo_stream { flash.now[:notice] = "Habit was successfully updated!." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @habit.destroy

    respond_to do |format|
      format.html { redirect_to habits_path, notice: "Habit was successfully destroyed!." }
      format.turbo_stream { flash.now[:notice] = "Habit was successfully destroyed!." }
    end
  end

  def plus
    @habit.update(count: @habit.count + 1)
    render :result
  end

  def minus
    @habit.update(count: @habit.count - 1)
    render :result
  end
    



  private

  def set_habit
    @habit = current_user.habits.find(params[:id])
  end

  def habit_params
    params.require(:habit).permit(:name, :count)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def format_date(date)
        date.strftime("%v %H:%M %p")
    end

    def render_turbo_stream_flash_messages
        turbo_stream.prepend 'flash_message', partial: 'layouts/flashes' 
    end
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/habits/_form.html.erb
<%= form_with(model: habit, class: "w-full") do |form| %>
  <% if habit.errors.any? %>
    <div class="mb-2 w-1/2 mx-auto bg-rose-200 rounded">
      <p class="p-2 text-sm font-bold text-center text-rose-500 animate-pulse"><%= heroicon "exclamation-triangle", options: { class: "inline-block mr-3" } %> <%= habit.errors.full_messages.to_sentence %></p>
    </div>
  <% end %>
  <div class="flex justify-center">
    <%= form.text_field :name, placeholder: "eg: Read Everyday", class: "w-2/3 text-center text-sm focus:border-pink-400 focus:ring-0 border border-pink-400 caret-pink-500 rounded-l-2xl" %>
    <%= form.submit(class: "cursor-pointer w-1/3 py-3 px-2 text-xs md:text-sm font-bold bg-pink-600 text-pink-100 rounded-r-2xl") %>
  </div>
<% end %>

app/views/habits/_habit.html.erb
  	<%= turbo_frame_tag(habit, class: "block w-full md:w-3/4 lg:w-1/2") do %>
  <div class="relative  p-5 bg-white text-gray-500 rounded-lg shadow-lg">
    <div class="absolute top-0 right-0 md:left-0 transform -translate-x-3 -translate-y-3">
      <awards-badge class="flex items-center space-x-1 text-xs">
        <!-- <img src="/images/medal.png" alt="medal icon" width="30" oncontextmenu="return false;">
					<img src="/images/trophy.png" alt="medal icon" width="30" oncontextmenu="return false;">
					<img src="/images/trophy(2).png" alt="medal icon" width="30" oncontextmenu="return false;"> -->
        <p class="p-1 bg-gray-400 text-gray-800 rounded">silver</p>
        <p class="p-1 bg-yellow-400 text-yellow-800 rounded">gold</p>
      </awards-badge>
    </div>
    <div class="pt-5 mb-5 md:flex items-center justify-between space-y-2 md:space-y-0">
      <p class="text-2xl font-bold text-gray-900 "><%= habit.name %></p>
      <div class="flex space-x-2 text-white">
        <%= button_to "-", minus_habit_path(habit), class: "py-1 px-3 font-extrabold bg-red-400 hover:bg-red-300 rounded-lg shadow hover:scale-105 transition duration-300" %>
        <div class="flex items-center justify-center py-1 px-3 text-sm bg-yellow-300 text-yellow-600 rounded-full">
          <p id="<%= dom_id(habit, 'habit_counter') %>"><%= habit.count %> Days</p>
        </div>
        <%= button_to "+", plus_habit_path(habit), class: "py-1 px-3 font-extrabold bg-green-400 hover:bg-green-500 rounded-lg shadow hover:scale-105 transition duration-300" %>
      </div>
    </div>
    <div class="space-y-2">
      <div class="text-xs md:text-sm">
        <p id="<%= dom_id(habit, 'time_update') %>">last updated: <%= format_date(habit.updated_at) %></p>
      </div>
      <div class="px-1 bg-gray-200 rounded-full">
        <%= render 'habit_streak_markers', habit: habit %>
      </div>
      <action-buttons class="!mt-7 flex justify-end space-x-4">
        <%= link_to edit_habit_path(habit) do %>
          <%= heroicon "pencil-square" %>
          <% end %>
        <%= button_to habit_path(habit), method: :delete, data: { turbo_confirm: "Are you sure?" } do %>
          <%= heroicon "trash" %>
          <% end %>
       
      </action-buttons>
    </div>
  </div>
<% end %>

app/views/habits/_habit_streak_markers.html.erb
<div id="<%= dom_id(habit, 'habit_markers') %>" class="pt-1">
    <% habit.count.times do %>
    <div class="inline-block p-2 bg-green-600 rounded"></div>
    <% end %>
</div>

app/views/habits/create.turbo_stream.erb
<!-- replace the form with empty form -->
<%= turbo_stream.replace "new_habit" do %>
  <% turbo_frame_tag "new_habit" do %>
    <%= render 'form', habit: Habit.new %>
  <% end %>
<% end %>

<%= turbo_stream.prepend 'habits', @habit %>
<%= render_turbo_stream_flash_messages %>

app/views/habits/destroy.turbo_stream.erb
<%= turbo_stream.remove @habit %>
<%= render_turbo_stream_flash_messages %>

app/views/habits/edit.html.erb
<div class="flex items-center justify-center">
  <div class="w-full md:w-3/4 lg:w-1/2 space-y-4">
    <h2 class="text-2xl md:text-4xl font-bold">Edit <%= @habit.name %></h2>
    <%= turbo_frame_tag @habit do %>
    <%= link_to sanitize("&larr; Cancel"), habits_path, class: "mb-8 inline-block py-2 px-6 text-center bg-gray-100 text-gray-600 rounded-lg shadow" %>
    <%= render 'form', habit: @habit %>
    <% end %>
  </div>
</div>

app/views/habits/index.html.erb
<div class="flex flex-col items-center space-y-6">
  <h2
			class="p-5 text-3xl md:text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-pink-600 via-purple-600 to-pink-800 ">
    Track Your Habits</h2>
  <div class="pb-16 w-full md:w-3/4 lg:w-1/2">
    <%= turbo_frame_tag "new_habit" do %>
      <%= render 'form', habit: @habit %>
    <% end %>
  </div>
  <%= turbo_frame_tag("habits", class: "contents space-y-6") do %>
    <%= render @habits %>
  <% end %>
</div>

app/views/habits/new.html.erb
<h2 class="mb-4 text-2xl md:text-4xl font-bold text-center">Create new habit</h2>
<%= turbo_frame_tag "new_habit" do %>
<%= render 'form', habit: @habit %>
<% end %>

app/views/habits/result.turbo_stream.erb
<%= turbo_stream.replace dom_id(@habit, 'habit_counter') do %>
  <p id="<%= dom_id(@habit, 'habit_counter') %>"><%= @habit.count %> Days</p>
<% end %>
<%= turbo_stream.replace dom_id(@habit, 'time_update') do %>
  <p id="<%= dom_id(@habit, 'time_update') %>">last updated: <%= format_date(@habit.updated_at) %></p>
<% end %>
<%= turbo_stream.replace dom_id(@habit, 'habit_markers') do %>
  <%= render 'habit_streak_markers', habit: @habit %>
<% end %>

app/views/habits/update.turbo_stream.erb
<%= turbo_stream.prepend "habits", @habit %>
<%= render_turbo_stream_flash_messages %>

app/views/layouts/_flashes.html.erb
<% if notice.present? %>
<div id="fadeout" class="px-5 flex justify-end">
<div class="w-full md:w-2/5 lg:w-1/4  mt-5 p-3 text-sm text-center bg-black text-yellow-300 rounded-full">
    <%= notice %>
</div>
</div>
<% end %>

app/views/layouts/_header.html.erb
<header class="pb-2 flex items-center justify-between bg-pink-500 text-pink-100">
  <%= render 'layouts/logo' %>
  <div class="mr-5 flex items-center font-bold space-x-3">
    <% if user_signed_in? %>
      <%= link_to current_user.username.upcase, edit_user_registration_path, class: "text-sm text-white" %>
      <%= link_to image_tag("power.svg", width: "40"), destroy_user_session_path, data: {turbo_method: :delete}, class: ""  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "py-2 px-4 md:px-6 bg-pink-100 text-pink-600 rounded shadow" %>
      <%= link_to "Login", new_user_session_path, class: "py-2 px-4 md:px-6 border border-pink-100 rounded shadow" %>
    <% end %>
  </div>
</header>

app/views/layouts/_logo.html.erb
<div class="ml-5 h-20 w-20 bg-pink-500 border-b-2 border-pink-100  rounded-full relative overflow-hidden">
  <div class="h-8 w-8 bg-white absolute top-0 left-0 rounded-full transform rotate-45">
    <div class="relative h-8 w-8 tranform -rotate-45">
      <div class=" absolute h-4 w-4 bottom-0 right-0  bg-black rounded-full"></div>
    </div>
  </div>
  <div class="h-8 w-8 bg-white absolute top-0 right-0 rounded-full transform -rotate-45">
    <div class="relative h-8 w-8 tranform rotate-45">
      <div class=" absolute h-4 w-4 bottom-0 left-0  bg-black rounded-full"></div>
    </div>
  </div>
  <h1 class="absolute top-0 right-0 text-lg text-white font-extrabold transform translate-y-10 -translate-x-3">Habitbi
  </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Habitbi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="font-serif bg-gradient-to-br from-pink-50 via-purple-100 to-gray-100">
    <%= render 'layouts/header' %>
    <div id="flash_message">
      <%= render 'layouts/flashes' %>
    </div>
    <main class="container mx-auto py-10 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/welcome/home.html.erb
<div>
  <h1 class="font-bold text-4xl text-red-500">Welcome#home</h1>
  <p>Find me in app/views/welcome/home.html.erb</p>
</div>